name: Singularity Build (native)
on:
  workflow_dispatch:
  push:
jobs:

  build:
    name: Build
    runs-on: ubuntu-18.04
    env:
      username: myoung3
      organization: kaufman-lab
      repository: geospatial_plus  
      tag: 4.1.0
    steps:
    - name: Set up Go 1.16
      uses: actions/setup-go@v1
      with:
        go-version: 1.16
      id: go

    - name: Install Dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y \
          build-essential \
          libssl-dev \
          uuid-dev \
          libgpgme11-dev \
          squashfs-tools \
          libseccomp-dev \
          pkg-config
    - name: Install Singularity
      env:
        SINGULARITY_VERSION: 3.8.1
        GOPATH: /tmp/go
      run: |
        mkdir -p $GOPATH
        sudo mkdir -p /usr/local/var/singularity/mnt && \
        mkdir -p $GOPATH/src/github.com/sylabs && \
        cd $GOPATH/src/github.com/sylabs && \
        wget -qO- https://github.com/sylabs/singularity/releases/download/v${SINGULARITY_VERSION}/singularity-ce-${SINGULARITY_VERSION}.tar.gz | \
        tar xzv && \
        cd singularity-ce-${SINGULARITY_VERSION} && \
        ./mconfig -p /usr/local && \
        make -C builddir && \
        sudo make -C builddir install          
          
    - name: git checkout
      uses: actions/checkout@v1

    - name: Log in to github container repository (using singularity)
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | singularity remote login -u ${{ env.username }} --password-stdin oras://ghcr.io
        singularity remote list
        
    - name: Build container and deploy
      env:
        SINGULARITY_RECIPE: ${{ env.repository }}${{ env.tag}}.def
        OUTPUT_CONTAINER: ${{ env.repository }}${{ env.tag}}.sif
      run: |
       ls 
       if [ -f "${SINGULARITY_RECIPE}" ]; then
            sudo -E singularity build ${OUTPUT_CONTAINER} ${SINGULARITY_RECIPE}
       else
           echo "${SINGULARITY_RECIPE} is not found."
           echo "Present working directory: $PWD"
           ls
       fi
       singularity push ${{ env.OUTPUT_CONTAINER }} oras://ghcr.io/${{ env.organization }}/${{ env.repository }}:${{ env.tag}} 

