name: Singularity Build
on: 
  workflow_dispatch:
  push:
    branches:
      - main
  # Do the builds on all pull requests (to test them), but don't deploy on PR (see below)
  pull_request: []
jobs:

  build:
    name: Build
    runs-on: ubuntu-18.04
    env: 
      username: myoung3
      organization: kaufman-lab
    strategy:
      fail-fast: false
      matrix:
        repository: [geospatial_plus, geospatial_plus_ml]
        tag: [4.1.0]
    steps:
    - name: Get changed definition files
      id: changed-files-def
      uses: tj-actions/changed-files@v9.1
      with:
        files: |
          .(def)$
            
    - name: Set up Go
      if: ( steps.changed-files-def.outputs.any_changed == 'true' | github.event_name == 'workflow_dispatch')
      uses: actions/setup-go@v1
      with:
        go-version: 1.16
      id: go

    - name: Install Dependencies
      if: ( steps.changed-files-def.outputs.any_changed == 'true' | github.event_name == 'workflow_dispatch')
      run: |
        sudo apt-get update && sudo apt-get install -y \
          build-essential \
          libssl-dev \
          uuid-dev \
          libgpgme11-dev \
          squashfs-tools \
          libseccomp-dev \
          pkg-config
          
    - name: Install Singularity
      if: ( steps.changed-files-def.outputs.any_changed == 'true' | github.event_name == 'workflow_dispatch')
      env:
        SINGULARITY_VERSION: 3.8.1
        GOPATH: /tmp/go
      run: |
        mkdir -p $GOPATH
        sudo mkdir -p /usr/local/var/singularity/mnt && \
        mkdir -p $GOPATH/src/github.com/sylabs && \
        cd $GOPATH/src/github.com/sylabs && \
        wget -qO- https://github.com/sylabs/singularity/releases/download/v${SINGULARITY_VERSION}/singularity-ce-${SINGULARITY_VERSION}.tar.gz | \
        tar xzv && \
        cd singularity-ce-${SINGULARITY_VERSION} && \
        ./mconfig -p /usr/local && \
        make -C builddir && \
        sudo make -C builddir install          
          
    - name: git checkout
      if: ( steps.changed-files-def.outputs.any_changed == 'true' | github.event_name == 'workflow_dispatch')
      uses: actions/checkout@v1

    - name: Build container
      if: ( steps.changed-files-def.outputs.any_changed == 'true' | github.event_name == 'workflow_dispatch')
      env:
        SINGULARITY_RECIPE: ${{ matrix.repository }}${{ matrix.tag}}.def
        OUTPUT_CONTAINER: ${{ matrix.repository }}${{ matrix.tag}}.sif
        MODIFIED_FILES: ${{ steps.changed-files.outputs.all_modified_files }}
      run: |
       ls 
       echo "current file: ${SINGULARITY_RECIPE}"
       echo "modified files: ${MODIFIED_FILES}"
       
       if echo "${MODIFIED_FILES}" |  grep -q ${SINGULARITY_RECIPE}; then 
         if [ -f "${SINGULARITY_RECIPE}" ]; then
           sudo -E singularity build ${OUTPUT_CONTAINER} ${SINGULARITY_RECIPE}
         else
           echo "${SINGULARITY_RECIPE} is not found."
           echo "Present working directory: $PWD"
         fi
       else
         echo "skipping unchanged file"
       fi
       
    - name: log in to github container registry and deploy
      if: (github.event_name != 'pull_request') && ( steps.changed-files-def.outputs.any_changed == 'true' | github.event_name == 'workflow_dispatch')
      env:
        SINGULARITY_RECIPE: ${{ matrix.repository }}${{ matrix.tag}}.def
        OUTPUT_CONTAINER: ${{ matrix.repository }}${{ matrix.tag}}.sif
        MODIFIED_FILES: ${{ steps.changed-files.outputs.all_modified_files }}
      run: |
       if echo "${MODIFIED_FILES}" |  grep -q ${SINGULARITY_RECIPE}; then 
         echo ${{ secrets.GITHUB_TOKEN }} | singularity remote login -u ${{ env.username }} --password-stdin oras://ghcr.io
         singularity remote list
         singularity push ${{ env.OUTPUT_CONTAINER }} oras://ghcr.io/${{ env.organization }}/${{ matrix.repository }}:${{ matrix.tag}} 
       else
         echo "skipping unchanged file"
       fi
       

